#!/bin/sh
# Update UFO after any edits other than with FontForge and prior to commit

# Stop on any errors
set -e

# Check and normalize all UFOs first -- assumes no other steps de-normalize
echo
echo "Normalizing UFOs..."
psfnormalize -p scrlevel=w -p checkfix=check source/masters/Lateef-ExtraLight.ufo  &
psfnormalize -p scrlevel=w -p checkfix=check source/masters/Lateef-Regular.ufo  &
psfnormalize -p scrlevel=w -p checkfix=check source/masters/Lateef-ExtraBold.ufo  &
wait

echo
echo "Updating glyph orders in Regular..."
# setting both to the same order
psfsetglyphorder -q -p checkfix=none --header DesignerOrder,DesignerOrder --field public.glyphOrder,com.schriftgestaltung.glyphOrder -i source/glyph_data.csv source/masters/*-Regular.ufo

echo
echo "Updating production names in Regular..."
psfsetpsnames -q -p checkfix=none -i source/glyph_data.csv source/masters/*-Regular.ufo

echo
echo "Syncing glyph orders, psnames, and other metadata to other UFOs..."
psfsyncmasters -p scrlevel=w --complex source/lateef.designspace

echo
echo "Syncing kerning information from Regular to ExtraLight and ExtraBold UFOs..."
# kerning.plist and groups.plist
cp source/masters/Lateef-Regular.ufo/kerning.plist \
   source/masters/Lateef-Regular.ufo/groups.plist \
      source/masters/Lateef-ExtraLight.ufo/
cp source/masters/Lateef-Regular.ufo/kerning.plist \
   source/masters/Lateef-Regular.ufo/groups.plist \
      source/masters/Lateef-ExtraBold.ufo/

echo
echo "Updating woff metadata files..."
psfmakewoffmetadata -q -n lateef      -i org.sil.fonts -o source/Lateef-WOFF-metadata.xml      source/masters/*-Regular.ufo

echo
echo "preflight completed!"
