#!/bin/sh
# Update UFO after any edits other than with FontForge and prior to commit

# Stop on any errors
set -e

# Check and normalize all UFOs first -- assumes no other steps de-normalize
echo
echo "Normalizing UFOs..."
psfnormalize -p scrlevel=w -p checkfix=check source/masters/Lateef-ExtraLight.ufo  &
psfnormalize -p scrlevel=w -p checkfix=check source/masters/Lateef-Regular.ufo  &
psfnormalize -p scrlevel=w -p checkfix=check source/masters/Lateef-ExtraBold.ufo  &
wait

echo
echo "Updating glyph orders in Regular..."
# setting both to the same order
psfsetglyphorder -q -p checkfix=none --header DesignerOrder,DesignerOrder --field public.glyphOrder,com.schriftgestaltung.glyphOrder -i source/glyph_data.csv source/masters/*-Regular.ufo

echo
echo "Updating production names in Regular..."
psfsetpsnames -q -p checkfix=none -i source/glyph_data.csv source/masters/*-Regular.ufo

echo
echo "Syncing glyph orders, psnames, and other metadata to other UFOs..."
psfsyncmasters -p scrlevel=w --complex source/lateef.designspace

echo
echo "Syncing kerning information from Regular to ExtraLight and ExtraBold UFOs..."
# kerning.plist and groups.plist
cp source/masters/Lateef-Regular.ufo/kerning.plist \
   source/masters/Lateef-Regular.ufo/groups.plist \
      source/masters/Lateef-ExtraLight.ufo/
cp source/masters/Lateef-Regular.ufo/kerning.plist \
   source/masters/Lateef-Regular.ufo/groups.plist \
      source/masters/Lateef-ExtraBold.ufo/

echo
echo "Updating classes.xml..."
python3 tools/absgenclasses.py -p scrlevel=w -c source/classes.xml -i source/glyph_data.csv source/masters/*-Regular.ufo source/classes.xml

echo
echo "Building internal fea..."
psfmakefea -q -o source/masters/Lateef-Regular.ufo/features.fea    -l logs/Lateef-Regular-psfmakefea.log    -i source/opentype/main.feax -c source/classes.xml --omitaps "_above _aboveLeft _below _center _ring _through above aboveLeft below center ring through entry exit alefUnused" source/masters/Lateef-Regular.ufo    &
psfmakefea -q -o source/masters/Lateef-ExtraLight.ufo/features.fea -l logs/Lateef-ExtraLight-psfmakefea.log -i source/opentype/main.feax -c source/classes.xml --omitaps "_above _aboveLeft _below _center _ring _through above aboveLeft below center ring through entry exit alefUnused _none" source/masters/Lateef-ExtraLight.ufo &
psfmakefea -q -o source/masters/Lateef-ExtraBold.ufo/features.fea  -l logs/Lateef-ExtraBold-psfmakefea.log  -i source/opentype/main.feax -c source/classes.xml --omitaps "_above _aboveLeft _below _center _ring _through above aboveLeft below center ring through entry exit alefUnused _none" source/masters/Lateef-ExtraBold.ufo  &
wait

echo
echo "Updating woff metadata files..."
psfmakewoffmetadata -q -n lateef      -i org.sil.fonts -o source/Lateef-WOFF-metadata.xml      source/masters/*-Regular.ufo

echo
echo "preflight completed!"
