#!/bin/sh
# Update UFO after editing with FontForge and prior to commit

# Stop on any errors
set -e

# Check and normalize all UFOs first -- assumes no other steps de-normalize
echo
echo "Fixing FontForge debris and normalizing UFOs..."
psffixffglifs -p checkfix=fix source/masters/*-Light.ufo    &
psffixffglifs -p checkfix=fix source/masters/*-Regular.ufo  &
psffixffglifs -p checkfix=fix source/masters/*-Black.ufo    &
wait

echo
echo "Updating glyph orders in Regular..."
# setting both to the same order
psfsetglyphorder -q -p checkfix=none --header DesignerOrder,DesignerOrder --field public.glyphOrder,com.schriftgestaltung.glyphOrder -i source/glyph_data.csv source/masters/*-Regular.ufo

echo
echo "Updating production names in Regular..."
psfsetpsnames -q -p checkfix=none -i source/glyph_data.csv source/masters/*-Regular.ufo

echo
echo "Syncing glyph orders, psnames, and other metadata to other UFOs..."
psfsyncmasters source/*-RB.designspace

echo
echo "Updating woff metadata file..."
psfmakewoffmetadata -q -n Lateef -i org.sil.fonts source/masters/*-Regular.ufo

echo
echo "preflightff completed!"
