#!/bin/sh

# This section contains commands that run every time
echo
echo "Converting Glyphs to UFO3..."
psfglyphs2ufo --nofea source/Lateef.glyphs source

# Continue with normal preflight
./preflight
