#!/bin/sh
# Update UFO after editing with FontForge and prior to commit

# Stop on any errors
set -e

# Check and normalize all UFOs first -- assumes no other steps de-normalize
echo
echo "Fixing FontForge debris and normalizing UFOs..."
psffixffglifs -p checkfix=fix source/masters/Lateef-ExtraLight.ufo    &
psffixffglifs -p checkfix=fix source/masters/Lateef-Regular.ufo  &
psffixffglifs -p checkfix=fix source/masters/Lateef-ExtraBold.ufo    &
wait

echo
echo "Updating glyph orders in Regular..."
# setting both to the same order
psfsetglyphorder -q -p checkfix=none --header DesignerOrder,DesignerOrder --field public.glyphOrder,com.schriftgestaltung.glyphOrder -i source/glyph_data.csv source/masters/*-Regular.ufo

echo
echo "Updating production names in Regular..."
psfsetpsnames -q -p checkfix=none -i source/glyph_data.csv source/masters/*-Regular.ufo

echo
echo "Syncing glyph orders, psnames, and other metadata to other UFOs..."
psfsyncmasters source/lateef.designspace

echo
echo "Updating woff metadata files..."
psfmakewoffmetadata -q -n lateef      -i org.sil.fonts -o source/Lateef-WOFF-metadata.xml      source/masters/*-Regular.ufo
psfmakewoffmetadata -q -n lateefbook  -i org.sil.fonts -o source/LateefBook-WOFF-metadata.xml  source/masters/*-Regular.ufo
psfmakewoffmetadata -q -n lateeflight -i org.sil.fonts -o source/LateefLight-WOFF-metadata.xml source/masters/*-Regular.ufo

echo
echo "preflightff completed!"
