#!/bin/sh
# script to convert UFOs to glyphs file for editing
DESIGNSPACE=source/lateef.designspace
OUTPUT=source/Lateef-Regular.glyphs

echo "Converting UFO(s) in '$DESIGNSPACE' to '$OUTPUT'"
psfufo2glyphs $DESIGNSPACE $OUTPUT